"""
Prepare Libri4Mix / Libri5Mix for CA-MoSE — Phase 1 (P1-A5).

The standard JorisCos/LibriMix repo only ships Libri2Mix and Libri3Mix.  This
script uses the shakeddovrat/librimix fork, which adds Libri4Mix/Libri5Mix
metadata and generation, to produce the higher-count mixtures needed for the
N=4,5 training data (P3-A1) and the break-point curve (P5-B1).

It is a deliberate sibling of ``prepare_librimix.py`` (the proven Phase-0
Libri3Mix path) rather than an edit to it, so the M0 baseline generation stays
untouched.  The LibriSpeech download logic is reused directly from that module.

Note on the train split
-----------------------
Like ``prepare_librimix.py``, the train-360 split requires LibriSpeech
train-clean-360 (~25 GB) and is skipped by default.  Pass ``--include-train``
with train-clean-360 present at ``--librispeech-dir`` to generate it.

Note on the loader
------------------
``discover_librimix_samples`` (data/mixer_stub.py) currently loads three
speakers only.  Discovering these Libri4/5Mix sets from disk needs an N-aware
loader — that is the P3-A1 follow-up; this script only produces the data.

Usage
-----
    python data/prepare_librimix_highn.py --output-dir /path/to/datasets
    python data/prepare_librimix_highn.py --output-dir /path/to/datasets \\
        --n-src 4 --librispeech-dir /path/to/existing/librispeech
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

# Reuse the proven LibriSpeech download from the Phase-0 script (same folder).
from data.prepare_librimix import download_librispeech

# ── URLs and constants ────────────────────────────────────────────────────────

# Fork of JorisCos/LibriMix that adds Libri4Mix / Libri5Mix metadata + generation.
LIBRIMIX_HIGHN_REPO_URL = "https://github.com/shakeddovrat/librimix"

SUPPORTED_N_SRC: tuple[int, ...] = (4, 5)

# Only dev/test are generated by default; train-360 is opt-in (see module docstring).
_DEV_TEST_CSV_TEMPLATE = ["mixture_dev_mix_both.csv", "mixture_test_mix_both.csv"]
_TRAIN_CSV = "mixture_train-360_mix_both.csv"

REQUIRED_SUBSETS = ["dev", "test"]


# ── Repo cloning ──────────────────────────────────────────────────────────────


def clone_librimix_highn(tools_dir: Path) -> Path:
    """
    Shallow-clone the shakeddovrat/librimix fork into tools_dir/librimix_highn.

    Returns the path to the cloned repo.  Skips if already present.
    """
    repo_dir = tools_dir / "librimix_highn"
    if repo_dir.is_dir() and (repo_dir / "metadata").is_dir():
        print(f"  [skip] Libri4/5Mix repo already at {repo_dir}")
        return repo_dir

    tools_dir.mkdir(parents=True, exist_ok=True)
    print(f"  [clone] {LIBRIMIX_HIGHN_REPO_URL}")
    subprocess.run(
        ["git", "clone", "--depth", "1", LIBRIMIX_HIGHN_REPO_URL, str(repo_dir)],
        check=True,
    )
    print(f"  [ok] {repo_dir}")
    return repo_dir


# ── Generation ────────────────────────────────────────────────────────────────


def _find_generation_script(repo: Path) -> Path:
    """Locate create_librimix_from_metadata.py inside the cloned repo."""
    candidates = [
        repo / "create_librimix_from_metadata.py",
        repo / "scripts" / "create_librimix_from_metadata.py",
    ]
    for path in candidates:
        if path.exists():
            return path
    raise FileNotFoundError(
        f"Cannot find create_librimix_from_metadata.py in {repo}. "
        "The librimix fork structure may have changed — check the clone."
    )


def _make_filtered_metadata(repo: Path, work_dir: Path, n_src: int, include_train: bool) -> Path:
    """
    Copy the LibriNMix metadata CSVs into a private directory.

    When include_train is False (default) the train-360 CSV is excluded so the
    generator never reads train-clean-360.  Returns the directory to pass as
    --metadata_path (the parent holding ``Libri{N}Mix/``).
    """
    src_dir = repo / "metadata" / f"Libri{n_src}Mix"
    dst_dir = work_dir / "metadata_filtered" / f"Libri{n_src}Mix"
    dst_dir.mkdir(parents=True, exist_ok=True)

    csvs = list(_DEV_TEST_CSV_TEMPLATE)
    if include_train:
        csvs.append(_TRAIN_CSV)

    for csv_name in csvs:
        src = src_dir / csv_name
        dst = dst_dir / csv_name
        if not dst.exists():
            if not src.exists():
                raise FileNotFoundError(
                    f"Expected metadata CSV not found: {src}\n"
                    f"The fork may not provide Libri{n_src}Mix metadata — check the clone."
                )
            shutil.copy2(str(src), str(dst))

    return work_dir / "metadata_filtered"


def generate_librimix_highn(
    repo: Path,
    librispeech_dir: Path,
    output_dir: Path,
    n_src: int,
    *,
    include_train: bool = False,
) -> Path:
    """
    Run the fork's generation script to produce Libri{n_src}Mix.

    Generates 16 kHz, max mode, mix_both type.  By default generates dev and
    test only.  Skips entirely if test/mix_both already contains WAV files.
    Returns the Libri{n_src}Mix data root.
    """
    if n_src not in SUPPORTED_N_SRC:
        raise ValueError(f"n_src must be one of {SUPPORTED_N_SRC}, got {n_src}")

    librinmix_out = output_dir / f"Libri{n_src}Mix"
    test_mix = librinmix_out / "wav16k" / "max" / "test" / "mix_both"
    if test_mix.is_dir() and any(test_mix.glob("*.wav")):
        print(f"  [skip] Libri{n_src}Mix test split already at {librinmix_out}")
        return librinmix_out

    script = _find_generation_script(repo)
    filtered_meta = _make_filtered_metadata(repo, output_dir / "tools", n_src, include_train)

    ls_root = librispeech_dir / "LibriSpeech"
    if not ls_root.is_dir():
        ls_root = librispeech_dir

    output_dir.mkdir(parents=True, exist_ok=True)

    splits = "dev + test" + (" + train-360" if include_train else "")
    print(f"  [generate] Libri{n_src}Mix ({splits}) -> {librinmix_out}")
    print(f"    script:      {script.name}")
    print(f"    librispeech: {ls_root}")
    print(f"    metadata:    {filtered_meta}")
    print("    This may take 30–90 minutes depending on disk speed.")

    cmd = [
        sys.executable,
        str(script),
        "--librispeech_path",
        str(ls_root),
        "--metadata_path",
        str(filtered_meta),
        "--librimix_path",
        str(output_dir),
        "--n_src",
        str(n_src),
        "--freqs",
        "16000",
        "--modes",
        "max",
        "--types",
        "mix_both",
    ]
    subprocess.run(cmd, check=True)
    print(f"  [ok] {librinmix_out}")
    return librinmix_out


# ── Layout verification ───────────────────────────────────────────────────────


def verify_layout(data_root: Path, n_src: int) -> None:
    """
    Verify data_root matches the LibriMix layout for n_src speakers.

    Checks {data_root}/wav16k/max/{subset}/{stream_dir}/ for subset in
    [dev, test] and stream_dir in [mix_both, s1..s{n_src}].  Raises RuntimeError
    listing every missing directory.
    """
    wav_root = data_root / "wav16k" / "max"
    if not wav_root.is_dir():
        raise RuntimeError(
            f"wav16k/max/ not found under {data_root}.\n"
            f"Did the Libri{n_src}Mix generation step complete successfully?"
        )

    stream_dirs = ["mix_both"] + [f"s{i}" for i in range(1, n_src + 1)]
    missing: list[str] = []
    for subset in REQUIRED_SUBSETS:
        for stream_dir in stream_dirs:
            d = wav_root / subset / stream_dir
            if not d.is_dir():
                missing.append(f"  {d}")

    if missing:
        raise RuntimeError(
            "Layout verification failed — missing directories:\n"
            + "\n".join(missing)
            + "\n\nRe-run prepare_librimix_highn.py or check the generation output."
        )

    print("  Layout OK:")
    streams = ", ".join(stream_dirs)
    for subset in REQUIRED_SUBSETS:
        print(f"    {data_root}/wav16k/max/{subset}/  [{streams}]")


# ── CLI ───────────────────────────────────────────────────────────────────────


def _parse_n_src(value: str) -> list[int]:
    return [int(v.strip()) for v in value.split(",") if v.strip()]


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Download LibriSpeech, generate Libri4Mix / Libri5Mix via the "
            "shakeddovrat/librimix fork, and verify the layout (P1-A5)."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        type=Path,
        metavar="DIR",
        help="Root directory for generated data. Libri{N}Mix lands in <DIR>/Libri{N}Mix/.",
    )
    parser.add_argument(
        "--librispeech-dir",
        type=Path,
        default=None,
        metavar="DIR",
        help="Where LibriSpeech is/goes. Defaults to <output-dir>/librispeech.",
    )
    parser.add_argument(
        "--n-src",
        type=str,
        default="4,5",
        metavar="LIST",
        help="Comma-separated speaker counts to generate (default: 4,5).",
    )
    parser.add_argument(
        "--include-train",
        action="store_true",
        help=(
            "Also generate the train-360 split. "
            "Requires LibriSpeech train-clean-360 at --librispeech-dir."
        ),
    )
    args = parser.parse_args()

    n_src_values = _parse_n_src(args.n_src)
    for n in n_src_values:
        if n not in SUPPORTED_N_SRC:
            parser.error(f"--n-src values must be in {SUPPORTED_N_SRC}, got {n}")

    output_dir: Path = args.output_dir.resolve()
    librispeech_dir: Path = (
        args.librispeech_dir.resolve() if args.librispeech_dir else output_dir / "librispeech"
    )

    print("=" * 60)
    print("CA-MoSE  |  Prepare Libri4Mix / Libri5Mix  |  Phase 1 (P1-A5)")
    print("=" * 60)
    print(f"  output dir:      {output_dir}")
    print(f"  librispeech dir: {librispeech_dir}")
    print(f"  speaker counts:  {n_src_values}")
    if args.include_train:
        print("  train split:     yes (requires train-clean-360)")
    else:
        print("  train split:     no  (use --include-train to add it)")
    print()

    print("Step 1 / 4  Download LibriSpeech")
    download_librispeech(librispeech_dir)
    print()

    print("Step 2 / 4  Clone Libri4/5Mix repo")
    repo = clone_librimix_highn(output_dir / "tools")
    print()

    print("Step 3 / 4  Generate mixtures")
    data_roots: list[Path] = []
    for n in n_src_values:
        data_roots.append(
            generate_librimix_highn(
                repo, librispeech_dir, output_dir, n, include_train=args.include_train
            )
        )
    print()

    print("Step 4 / 4  Verify layout")
    for n, data_root in zip(n_src_values, data_roots, strict=True):
        verify_layout(data_root, n)
    print()

    print("=" * 60)
    print("Done.  Generated data roots:")
    for data_root in data_roots:
        print(f"  {data_root}")
    print("=" * 60)


if __name__ == "__main__":
    main()
